### ISSUE TITLE
Add support for arbitrary test case names

### ISSUE THREAD

**Issue by ncihnegn** [JCash/jctest#18]
Now ```TEST_CASE("multiply")``` doesn't compile.

**Comment by ncihnegn** [comment]
@JCash Could you please look into this? With this, I will be able to migrate from doctest.

**Comment by JCash** [comment]
Hmm, now I'm confused.
You added support for `TEST_CASE(symbolname)` but it was incorrect?

It should have been `TEST_CASE("my custom string")`?

Is the first case even proper doctest syntax?

**Comment by ncihnegn** [comment]
> Hmm, now I'm confused.
> You added support for `TEST_CASE(symbolname)` but it was incorrect?
> 
> It should have been `TEST_CASE("my custom string")`?
> 
> Is the first case even proper doctest syntax?

```TEST_CASE(multiply)``` works but ```TEST_CASE("multiply")``` doesn't.
In doctest, I always use ```TEST_CASE("test")```.

**Comment by JCash** [comment]
Yes, but is it even _possible_ to write `TEST_CASE(multiply)` ?

**Comment by ncihnegn** [comment]
Probably not. My impression is it assumes ```char*```.

**Comment by JCash** [comment]
Ok, so I wonder howcome you implemented it that way, and not the way doctest works?

**Comment by ncihnegn** [comment]
Likely because it is easier.

**Comment by JCash** [comment]
Ok, but it wasn't correct, and now we have a feature that isn't compliant.

Oh well, I might take a look at this at some point, or remove it altogether.
